package com.wikiMovies.domain;
// Generated Jun 6, 2019 10:59:50 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Favoritos generated by hbm2java
 */
@Entity
@Table(name="FAVORITOS"
    ,schema="SYS"
)
public class Favoritos  implements java.io.Serializable {


     private FavoritosId id;
     private Usuario usuario;
     private BigDecimal puntuacion;

    public Favoritos() {
    }

	
    public Favoritos(FavoritosId id, Usuario usuario) {
        this.id = id;
        this.usuario = usuario;
    }
    public Favoritos(FavoritosId id, Usuario usuario, BigDecimal puntuacion) {
       this.id = id;
       this.usuario = usuario;
       this.puntuacion = puntuacion;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="usuario", column=@Column(name="USUARIO", nullable=false, length=100) ), 
        @AttributeOverride(name="pelicula", column=@Column(name="PELICULA", nullable=false, length=80) ) } )
    public FavoritosId getId() {
        return this.id;
    }
    
    public void setId(FavoritosId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USUARIO", nullable=false, insertable=false, updatable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="PUNTUACION", precision=22, scale=0)
    public BigDecimal getPuntuacion() {
        return this.puntuacion;
    }
    
    public void setPuntuacion(BigDecimal puntuacion) {
        this.puntuacion = puntuacion;
    }




}


