package com.wikiMovies.domain;
// Generated May 12, 2019 4:54:58 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Favoritos generated by hbm2java
 */
@Entity
@Table(name="FAVORITOS"
    ,schema="SYS"
)
public class Favoritos  implements java.io.Serializable {


     private FavoritosId id;
     private Pelicula pelicula;
     private BigDecimal puntuacion;

    public Favoritos() {
    }

	
    public Favoritos(FavoritosId id, Pelicula pelicula) {
        this.id = id;
        this.pelicula = pelicula;
    }
    public Favoritos(FavoritosId id, Pelicula pelicula, BigDecimal puntuacion) {
       this.id = id;
       this.pelicula = pelicula;
       this.puntuacion = puntuacion;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="usuario", column=@Column(name="USUARIO", nullable=false, length=50) ), 
        @AttributeOverride(name="pelicula", column=@Column(name="PELICULA", nullable=false, length=80) ) } )
    public FavoritosId getId() {
        return this.id;
    }
    
    public void setId(FavoritosId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PELICULA", nullable=false, insertable=false, updatable=false)
    public Pelicula getPelicula() {
        return this.pelicula;
    }
    
    public void setPelicula(Pelicula pelicula) {
        this.pelicula = pelicula;
    }

    
    @Column(name="PUNTUACION", precision=22, scale=0)
    public BigDecimal getPuntuacion() {
        return this.puntuacion;
    }
    
    public void setPuntuacion(BigDecimal puntuacion) {
        this.puntuacion = puntuacion;
    }




}


