package com.wikiMovies.domain;
// Generated Jun 2, 2019 12:33:37 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FavoritosId generated by hbm2java
 */
@Embeddable
public class FavoritosId  implements java.io.Serializable {


     private String usuario;
     private String pelicula;

    public FavoritosId() {
    }

    public FavoritosId(String usuario, String pelicula) {
       this.usuario = usuario;
       this.pelicula = pelicula;
    }
   


    @Column(name="USUARIO", nullable=false, length=50)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }


    @Column(name="PELICULA", nullable=false, length=80)
    public String getPelicula() {
        return this.pelicula;
    }
    
    public void setPelicula(String pelicula) {
        this.pelicula = pelicula;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FavoritosId) ) return false;
		 FavoritosId castOther = ( FavoritosId ) other; 
         
		 return ( (this.getUsuario()==castOther.getUsuario()) || ( this.getUsuario()!=null && castOther.getUsuario()!=null && this.getUsuario().equals(castOther.getUsuario()) ) )
 && ( (this.getPelicula()==castOther.getPelicula()) || ( this.getPelicula()!=null && castOther.getPelicula()!=null && this.getPelicula().equals(castOther.getPelicula()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUsuario() == null ? 0 : this.getUsuario().hashCode() );
         result = 37 * result + ( getPelicula() == null ? 0 : this.getPelicula().hashCode() );
         return result;
   }   


}


