package com.wikiMovies.domain;
// Generated Jun 2, 2019 12:33:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pelicula generated by hbm2java
 */
@Entity
@Table(name="PELICULA"
    ,schema="SYS"
)
public class Pelicula  implements java.io.Serializable {


     private String nombre;
     private String genero;
     private String font1;
     private String font2;
     private String font3;
     private String descripcion;
     private String resumen;
     private String trailer;
     private Set<Favoritos> favoritoses = new HashSet<Favoritos>(0);

    public Pelicula() {
    }

	
    public Pelicula(String nombre) {
        this.nombre = nombre;
    }
    public Pelicula(String nombre, String genero, String font1, String font2, String font3, String descripcion, String resumen, String trailer, Set<Favoritos> favoritoses) {
       this.nombre = nombre;
       this.genero = genero;
       this.font1 = font1;
       this.font2 = font2;
       this.font3 = font3;
       this.descripcion = descripcion;
       this.resumen = resumen;
       this.trailer = trailer;
       this.favoritoses = favoritoses;
    }
   
     @Id 

    
    @Column(name="NOMBRE", unique=true, nullable=false, length=80)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="GENERO", length=50)
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }

    
    @Column(name="FONT1", length=50)
    public String getFont1() {
        return this.font1;
    }
    
    public void setFont1(String font1) {
        this.font1 = font1;
    }

    
    @Column(name="FONT2", length=50)
    public String getFont2() {
        return this.font2;
    }
    
    public void setFont2(String font2) {
        this.font2 = font2;
    }

    
    @Column(name="FONT3", length=50)
    public String getFont3() {
        return this.font3;
    }
    
    public void setFont3(String font3) {
        this.font3 = font3;
    }

    
    @Column(name="DESCRIPCION", length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="RESUMEN", length=200)
    public String getResumen() {
        return this.resumen;
    }
    
    public void setResumen(String resumen) {
        this.resumen = resumen;
    }

    
    @Column(name="TRAILER", length=200)
    public String getTrailer() {
        return this.trailer;
    }
    
    public void setTrailer(String trailer) {
        this.trailer = trailer;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pelicula")
    public Set<Favoritos> getFavoritoses() {
        return this.favoritoses;
    }
    
    public void setFavoritoses(Set<Favoritos> favoritoses) {
        this.favoritoses = favoritoses;
    }




}


