package com.wikiMovies.domain;
// Generated May 12, 2019 4:54:58 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="USUARIO"
    ,schema="SYS"
)
public class Usuario  implements java.io.Serializable {


     private String email;
     private String nombre;
     private String apellidos;
     private BigDecimal edad;
     private String sexo;
     private String password;
     private Set<WikiGeneros> wikiGeneroses = new HashSet<WikiGeneros>(0);

    public Usuario() {
    }

	
    public Usuario(String email) {
        this.email = email;
    }
    public Usuario(String email, String nombre, String apellidos, BigDecimal edad, String sexo, String password, Set<WikiGeneros> wikiGeneroses) {
       this.email = email;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.edad = edad;
       this.sexo = sexo;
       this.password = password;
       this.wikiGeneroses = wikiGeneroses;
    }
   
     @Id 

    
    @Column(name="EMAIL", unique=true, nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="NOMBRE", length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="APELLIDOS", length=100)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="EDAD", precision=22, scale=0)
    public BigDecimal getEdad() {
        return this.edad;
    }
    
    public void setEdad(BigDecimal edad) {
        this.edad = edad;
    }

    
    @Column(name="SEXO", length=5)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    
    @Column(name="PASSWORD", length=10)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<WikiGeneros> getWikiGeneroses() {
        return this.wikiGeneroses;
    }
    
    public void setWikiGeneroses(Set<WikiGeneros> wikiGeneroses) {
        this.wikiGeneroses = wikiGeneroses;
    }




}


