package com.wikiMovies.domain;
// Generated Jun 2, 2019 12:33:37 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WikiGenerosId generated by hbm2java
 */
@Embeddable
public class WikiGenerosId  implements java.io.Serializable {


     private String usuario;
     private String descripcion;

    public WikiGenerosId() {
    }

    public WikiGenerosId(String usuario, String descripcion) {
       this.usuario = usuario;
       this.descripcion = descripcion;
    }
   


    @Column(name="USUARIO", nullable=false, length=100)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }


    @Column(name="DESCRIPCION", nullable=false, length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof WikiGenerosId) ) return false;
		 WikiGenerosId castOther = ( WikiGenerosId ) other; 
         
		 return ( (this.getUsuario()==castOther.getUsuario()) || ( this.getUsuario()!=null && castOther.getUsuario()!=null && this.getUsuario().equals(castOther.getUsuario()) ) )
 && ( (this.getDescripcion()==castOther.getDescripcion()) || ( this.getDescripcion()!=null && castOther.getDescripcion()!=null && this.getDescripcion().equals(castOther.getDescripcion()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUsuario() == null ? 0 : this.getUsuario().hashCode() );
         result = 37 * result + ( getDescripcion() == null ? 0 : this.getDescripcion().hashCode() );
         return result;
   }   


}


