package com.wikiMovies.domain;
// Generated May 12, 2019 4:54:58 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * WikiGeneros generated by hbm2java
 */
@Entity
@Table(name="WIKI_GENEROS"
    ,schema="SYS"
)
public class WikiGeneros  implements java.io.Serializable {


     private WikiGenerosId id;
     private Usuario usuario;

    public WikiGeneros() {
    }

    public WikiGeneros(WikiGenerosId id, Usuario usuario) {
       this.id = id;
       this.usuario = usuario;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="usuario", column=@Column(name="USUARIO", nullable=false, length=100) ), 
        @AttributeOverride(name="descripcion", column=@Column(name="DESCRIPCION", nullable=false, length=100) ) } )
    public WikiGenerosId getId() {
        return this.id;
    }
    
    public void setId(WikiGenerosId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USUARIO", nullable=false, insertable=false, updatable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


