package com.wikiMovies.domain;
// Generated Jun 2, 2019 12:33:37 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * WikiGeneros generated by hbm2java
 */
@Entity
@Table(name="WIKI_GENEROS"
    ,schema="SYS"
)
public class WikiGeneros  implements java.io.Serializable {


     private WikiGenerosId id;

    public WikiGeneros() {
    }

    public WikiGeneros(WikiGenerosId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="usuario", column=@Column(name="USUARIO", nullable=false, length=100) ), 
        @AttributeOverride(name="descripcion", column=@Column(name="DESCRIPCION", nullable=false, length=100) ) } )
    public WikiGenerosId getId() {
        return this.id;
    }
    
    public void setId(WikiGenerosId id) {
        this.id = id;
    }




}


